---
name: (Debian) Get Gitlab Runner repository installation script
ansible.builtin.get_url:
  url: "https://packages.gitlab.com/install/repositories/runner/{{ gitlab_runner_package_name }}/script.deb.sh"
  dest: "/tmp/{{ gitlab_runner_package_name }}.script.deb.sh"
  mode: 744

- name: (Debian) Install Gitlab Runner repository
  ansible.builtin.command: 
    creates: "/etc/apt/sources.list.d/runner_{{ gitlab_runner_package_name }}.list"
    cmd: "bash /tmp/gitlab_runner_package_name.script.deb.sh"
  become: true

- name: (Debian) Update Gitlab Runner package name with specific version
  ansible.builtin.set_fact:
    gitlab_runner_package: "{{ gitlab_runner_package_name }}={{ gitlab_runner_package_version }}"
    gitlab_runner_package_state: "present"
  when: gitlab_runner_package_version is defined

- name: (Debian) Update Gitlab Runner with latest version
  ansible.builtin.set_fact:
    gitlab_runner_package: "{{ gitlab_runner_package_name }}"
    gitlab_runner_package_state: "latest"
  when: gitlab_runner_package_version is not defined

- name: (Debian) Install Gitlab Runner
  ansible.builtin.apt:
    name: "{{ gitlab_runner_package }}"
    state: "{{ gitlab_runner_package_state }}"
  become: true