- name: Check if root crontab file is exists
  ansible.builtin.stat:
    path: /var/spool/cron/crontabs/root
  register: root_crontab_file
  become: yes

- name: Append Gitlab backup cronjob to root crontab
  ansible.builtin.blockinfile:  
    path: /var/spool/cron/crontabs/root
    block: |
      # Backup Gitlab data at 20:00 everyday
      0 20 * * * /opt/gitlab/bin/gitlab-backup create INCREMENTAL=yes CRON=1

      # Backup Gitlab data at 21:00 every Saturday
      0 21 * * 6 /opt/gitlab/bin/gitlab-backup create INCREMENTAL=yes CRON=1

      # Backup Gitlab data at 22:00 every first day of a month
      0 22 1 * * /opt/gitlab/bin/gitlab-backup create INCREMENTAL=yes CRON=1

      # Backup Gitlab configuration files at 20:30 everyday
      30 20 * * *  gitlab-ctl backup-etc && cd /etc/gitlab/config_backup && cp $(ls -t | head -n1) /secret/gitlab/backups/
  become: yes
  when: root_crontab_file.stat.exists

- name: Add Gitlab backup crontab
  ansible.builtin.template:
    src: "{{ root_crontab_template }}"
    dest: /var/spool/cron/crontabs/root
    owner: root
    group: root
    mode: 0600
  become: yes
  when: not root_crontab_file.stat.exists