- name: (Debian) Install Gitlab Runner
  import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: (Unix) Register GitLab Runner
  ansible.builtin.command: 
    cmd: |
      gitlab-runner register \
      --non-interactive \
      --url '{{ gitlab_runner_coordinator_url }}' \
      --registration-token '{{ gitlab_runner_registration_token }}' \
      --executor '{{ gitlab_runner_executor }}' \
      --docker-image '{{ gitlab_runner_init_docker_image }}:{{ gitlab_runner_init_docker_image_version }}' \
      --description '{{ gitlab_runner_description }}' \
      --tag-list '{{ gitlab_runner_tag_list }}' \
      --run-untagged='{{ gitlab_runner_run_untagged }}' \
      --locked='{{ gitlab_runner_locked }}' \
      --access-level='{{ gitlab_runner_protected }}'
  when: gitlab_runner_registration_token | string | length > 0
  become: true
