---
- name: Thainm5's Gitlab playbook
  hosts: gitlab_server
  
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

  roles:
    - gitlab